# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

# push, PR 이벤트 발생시 아래의 브랜치들에서 발생하게 되는 경우 작업
on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'develop'
      - 'feature/*'

# 실행해야 하는 작업들
jobs:
  CI:

    runs-on: ubuntu-latest

    # 작업 실행단계
    steps:
    # 체크아웃 및 JDK 세팅
    - name: Checkouy
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # Gradle 권한 부여
    - name: Grant Execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    
    # test하지 않고 빌드를 진행
    - name: Build with Gradle
      run: ./gradlew build -x test
      shell: bash
      
    # local환경으로 테스트 진행
    - name: Test with Gradle
      run: SPRING_PROFILES_ACTIVE=[local] ./gradlew clean test
      shell: bash
      
    # 해당 내용은 PR에서 테스트 진행시 오류가 발생한 경우 표시
    - name: Publich Unit Test Test Result
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }}
      with: 
        files: build/test-results/**/*.yml
    
